### ISSUE TITLE
UnicodeDecodeErrors on file read in Windows systems

### ISSUE THREAD

**Issue by rclee91** [abatomunkuev/static_site_generator#1]
File read on line 60: `file = open(file_path, mode='r') `generates a Error on Windows systems, causing no files to be generated.

Error code below:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 65: character maps to <undefined>

Suggested fix: 
Specify utf-8 encoding while opening the file.
For example: 
`file = open(file_path, mode='r', encoding="utf8")`
seems to solve the issue on Windows.

**Comment by abatomunkuev** [comment]
Issue has been fixed! Thank you!
