### ISSUE TITLE
New SSG Feature: Support --config with Config File

### ISSUE THREAD

**Issue by japneetsingh035** [abatomunkuev/static_site_generator#13]
Users want to be able to specify all of their SSG options in a JSON formatted configuration file instead of having to pass them all as command-line arguments every time. For example, consider the following config file, ./ssg-config.json:
```
  "input": "./site",
  "output": "./build",
  "stylesheet": "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css",
  "lang": "fr"
```
A user could run the SSG by doing either of the following:

```
# Option 1: use command line arguments:
ssg --input ./site --output ./build --stylesheet https://cdn.jsdelivr.net/npm/water.css@2/out/water.css --lang fr

# Option 2: use a config file
ssg --config ./ssg-config.json
```

The config file option means we can have a much shorter command, and instead store our options in a file.

**Comment by abatomunkuev** [comment]
Thank you Japneet. I have tested your code implementation. The tool is working!
