### ISSUE TITLE
Decoding issues in html content on Windows Machines

### ISSUE THREAD

**Issue by rclee91** [abatomunkuev/static_site_generator#3]
Original code on line 88: `html_p.append("<p>{content}</p>".format(content=paragraph.encode('utf-8')))` generates paragraphs with non decoded Unicode characters on Windows platforms. 

For example, a generated paragraph turns out to be 
`b'\xe2\x80\x9cGo! Where to?\xe2\x80\x9d'`
messing up readability.

Suggested fix:
Add a decode for utf-8
`html_p.append("<p>{content}</p>".format(content=paragraph.encode('utf-8').decode('utf-8')))`
seems to solve the issue.

**Comment by abatomunkuev** [comment]
Thank you for your suggestion! Issue has been resolved.
