### ISSUE TITLE
Remove dist/ from git

### ISSUE THREAD

**Issue by humphd** [abatomunkuev/static_site_generator#6]
We tend to put source code, but not generated files in git.  Things like build output, binaries, or a `dist/` folder often get generated from source code, so they don't need to get versioned.

I would remove `dist/` and add a `.gitignore` file so that it doesn't get added back. See https://github.com/github/gitignore/blob/master/Python.gitignore for an example.

**Comment by abatomunkuev** [comment]
Hello! 

I have removed _dist_ folder from the repository and added _.gitignore_ file
